<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales Checker</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }

        h1 {
            text-align: center;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .result {
            margin-top: 20px;
            padding: 10px;
            background-color: #e9f7ff;
            border-left: 4px solid #007bff;
            display: none;
        }

        .error {
            margin-top: 20px;
            padding: 10px;
            background-color: #f8d7da;
            border-left: 4px solid #f44336;
            display: none;
        }
    </style>
</head>
<body>

    <div class="container">
        <h1>Sales Checker</h1>
        <input type="text" id="salesQuery" placeholder="Enter Sales ID or Query">
        <button onclick="handleSearch()">Search</button>
        <div id="result" class="result"></div>
        <div id="error" class="error"></div>
    </div>

    <script>
        async function handleSearch() {
            const query = document.getElementById('salesQuery').value;
            const resultDiv = document.getElementById('result');
            const errorDiv = document.getElementById('error');

            resultDiv.style.display = 'none';
            errorDiv.style.display = 'none';

            if (!query) {
                errorDiv.textContent = 'Please enter a query.';
                errorDiv.style.display = 'block';
                return;
            }

            try {
                const response = await fetch(`https://script.google.com/macros/s/AKfycbyoVd2i1pqZpgnz7qfETAgvwr_voIFZ7bHBQ5jncxfURyZtiBceB-rThIGEaZI7lk4S/exec?query=${encodeURIComponent(query)}`, {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                });

                if (!response.ok) {
                    throw new Error('Failed to fetch data');
                }

                const data = await response.json();

                if (data.error) {
                    errorDiv.textContent = data.error;
                    errorDiv.style.display = 'block';
                } else {
                    resultDiv.textContent = JSON.stringify(data, null, 2);
                    resultDiv.style.display = 'block';
                }
            } catch (error) {
                errorDiv.textContent = 'An error occurred. Please try again.';
                errorDiv.style.display = 'block';
                console.error(error);
            }
        }
    </script>

</body>
</html>
