<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales Checker</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            background-color: #f4f4f9;
        }

        input, button {
            padding: 10px;
            font-size: 16px;
            margin: 10px;
        }

        #results {
            margin-top: 20px;
            padding: 10px;
            width: 80%;
            max-width: 600px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        }

        .result {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f9f9f9;
            border-radius: 5px;
            box-shadow: 0 1px 4px rgba(0, 0, 0, 0.1);
        }

        .error {
            color: red;
            font-weight: bold;
        }
    </style>
</head>
<body>

    <h1>Sales Checker</h1>
    <input type="text" id="query" placeholder="Enter Email, Phone, or ID" />
    <button onclick="handleSearch()">Search</button>

    <div id="results"></div>
    <div id="error" class="error"></div>

    <script>
        async function handleSearch() {
            const query = document.getElementById('query').value;
            const resultsContainer = document.getElementById('results');
            const errorContainer = document.getElementById('error');

            // Clear previous results
            resultsContainer.innerHTML = '';
            errorContainer.innerHTML = '';

            if (!query) {
                errorContainer.innerHTML = "Please enter a search term.";
                return;
            }

            try {
                const response = await fetch(`https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec?query=${encodeURIComponent(query)}`);
                const data = await response.json();

                if (data.error) {
                    errorContainer.innerHTML = data.error;
                    return;
                }

                // Display the data
                data.forEach(item => {
                    const resultBlock = document.createElement('div');
                    resultBlock.classList.add('result');
                    resultBlock.innerHTML = `<strong>Found Result:</strong> ${JSON.stringify(item, null, 2)}`;
                    resultsContainer.appendChild(resultBlock);
                });

            } catch (error) {
                console.error("Error:", error);
                errorContainer.innerHTML = "An error occurred while fetching data.";
            }
        }
    </script>

</body>
</html>
